--- 
  credentials:
    url: "https://yourserver.com/tsds-basic/"
    username: "username"
    password: "password"

  data:
    - tsds_name: interface
      telegraf_name: interface
      interval: 60
      metadata:
          - from: agent_host
            to: "node"
          - from: ifName
            to: "intf"
      optional_metadata:
          - from: ifAlias
            to: description
          # Take all the ip addresses and roll them up
          - from: ip_address_*
            to: interface_address
            field_name: value
      fields:
          - from: ifInErrors
            to: inerror
            rate: true
          - from: ifOutErrors
            to: outerror
            rate: true
          - from: ifHCInOctets
            to: input
            rate: true
          - from: ifHCOutOctets
            to: output
            rate: true
          - from: ifHCInUcastPkts
            to: inUcast
            rate: true
          - from: ifHCOutUcastPkts
            to: outUcast
            rate: true
          - from: ifInDiscards
            to: indiscard
            rate: true
          - from: ifOutDiscards
            to: outdiscard
            rate: true
          - from: ifOperStatus
            to: status



